apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-provider-kubernetes
  namespace: {{ .Values.panoscPortal.namespace }}
  labels:
    app: cloud-provider-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-provider-kubernetes
  template:
    metadata:
      labels:
        app: cloud-provider-kubernetes
    spec:
      serviceAccountName: cloud-provider-kubernetes-sa
      hostname: cloud-provider-kubernetes
      containers:
        - name: cloud-provider-kubernetes
          image: {{ .Values.dockerRegistry.url }}:{{ .Values.dockerRegistry.port }}/panosc-portal/cloud-provider-kubernetes
          ports:
              - containerPort: 3000
          envFrom:
            - configMapRef:
                name: cloud-provider-kubernetes-config
      {{- if and .Values.dockerRegistry.host .Values.dockerRegistry.username .Values.dockerRegistry.password }}
      imagePullSecrets:
        - name: {{ .Values.dockerRegistry.host | replace "." "-" }}
      {{ end }}
