apiVersion: v1
kind: ConfigMap
metadata:
  name: panosc-portal-postgres-config
  namespace: {{ .Values.panoscPortal.namespace }}
  labels:
    app: panosc-portal-postgres
data:
  CLOUD_PROVIDER_K8S_DATABASE_PASSWORD: {{ .Values.panoscPortalPostgres.password }}
